# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaf < Formula
  desc ""
  homepage ""
  version "0.1.60"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/birdayz/kaf/releases/download/v0.1.60/kaf_0.1.60_Darwin_arm64.tar.gz"
      sha256 "b3e2d5337ff8cea57485329fefc1315084f51bd010ee822e667e12ccc43e3dd8"

      def install
        bin.install "kaf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/birdayz/kaf/releases/download/v0.1.60/kaf_0.1.60_Darwin_x86_64.tar.gz"
      sha256 "b9d680296102c1cd3439d90be529fcd4c24b3ca3aed3d6b5d71c5bd73e1a671b"

      def install
        bin.install "kaf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/birdayz/kaf/releases/download/v0.1.60/kaf_0.1.60_Linux_arm64.tar.gz"
      sha256 "c35076f25783b685c5512db626c1b8725b9c91e0a397e6b7b3f389f5efb41f00"

      def install
        bin.install "kaf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/birdayz/kaf/releases/download/v0.1.60/kaf_0.1.60_Linux_x86_64.tar.gz"
      sha256 "4b1d4205eba34713285e6a8019a3ade1fd156fc911705d2b32f7c6cf6ae093bf"

      def install
        bin.install "kaf"
      end
    end
  end
end
